import axios from 'axios';

const accessToken = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoiUmlja3lwIiwiZW1haWwiOiJyZHAua3N1QGdtYWlsLmNvbSIsIm1vYmlsZSI6IisxMzMwOTQ5NTM1NSIsInVzZXJfaWQiOiJhMTM4NzFiMy0wN2FhLTRmM2QtODc3NS1mOTI5ZWUxMTVkYTIiLCJyb2xlIjp7ImlkIjozLCJjb2RlIjoidXNlciIsImxhYmVsIjoiVXNlciJ9LCJjbGllbnRfaWQiOiIxNTM4ODgzOS1jNTIzLTQzMmItODRjMy04YmVmYjhjYzU2ODgiLCJhY2Nlc3NfdG9rZW5fdHRsIjoiNzJociIsInJlZnJlc2hfdG9rZW5fdHRsIjoiMzBkIn0sImlhdCI6MTc1MTAwMjA5OSwiZXhwIjoxNzUxMjYxMjk5LCJpc3MiOiJhdXRoIn0.NOsk2nAbxtWB5lnGp_fVLV_2dflUJXGtTAF-QJ-uXMSzVjzZJLHGpTuRuM8PhixovhE96kNZTHlRPFDWa3wN0P2A3--R1P_MYkttNBd9tptjGV96Z_gtvwyoJKtPvIi08AJYSOB1Hpy-LOdPIdD2ACvoS5uuQmWP3uC9jbvFKKvxSRX3DxpW0MnuMtO0f7iv6GONwh-h80_pztq6CP6C1mnIVHh4hpP7R7vzNoeIIq3xRy-rU9xfcRYppMfsnYJl-x_lkk_zgvRY_DMYWQyu6df21F51nh7lBzYdhqEHSSyaAhaKKZVo6IXINkmBW29h782yzxS2eXwBMbqF9k3IHjeig358BvNixdrxOciDnLWI0G1E6wf8A6zxUZ9odrsjf5NotZo_CMD3T09LOXBUyh-g0RQFrSAxHFssmowENCA-kNjsWNEOEdMaN4nadXaAztwIgUVxfdF2d_X6rh_1ormeojBWC25MFoKH1-t_KRCTwskR-c_y3Zuc2d7OuhcH';

export const api = axios.create({
    baseURL: 'https://api.staging.opalinkapp.com',
    headers: {
        Authorization: `Bearer ${accessToken}`,
    },
});